### ISSUE TITLE
小米5s 一点就崩溃

### ISSUE THREAD

**Issue by lwj1994** [woxingxiao/BubbleSeekBar#1]

**Comment by woxingxiao** [comment]
你好，感谢反馈。麻烦帖下崩溃日志，我身边没有设备

**Comment by lwj1994** [comment]
Exception dispatching input event.
12-07 09:39:11.891 6183-6183/com.xw.samlpe.bubbleseekbar E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
12-07 09:39:11.892 6183-6183/com.xw.samlpe.bubbleseekbar E/MessageQueue-JNI: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7bf9d72 -- permission denied for this window type
                                                                                 at android.view.ViewRootImpl.setView(ViewRootImpl.java:609)
                                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:316)
                                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                                 at com.xw.repo.BubbleSeekBar$2.onAnimationStart(BubbleSeekBar.java:484)
                                                                                 at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1089)
                                                                                 at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1048)
                                                                                 at android.animation.ValueAnimator.start(ValueAnimator.java:1110)
                                                                                 at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
                                                                                 at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
                                                                                 at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
                                                                                 at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:486)
                                                                                 at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:389)
                                                                                 at android.view.View.dispatchTouchEvent(View.java:9306)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
                                                                                 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                 at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
                                                                                 at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                 at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
                                                                                 at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4278)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3830)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3887)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5970)
                                                                                 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5944)
                                                                                 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5905)
                                                                                 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6073)
                                                                             	at android.view.I
12-07 09:39:11.893 6183-6183/com.xw.samlpe.bubbleseekbar D/AndroidRuntime: Shutting down VM
12-07 09:39:11.893 6183-6183/com.xw.samlpe.bubbleseekbar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.xw.samlpe.bubbleseekbar, PID: 6183
                                                                           android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7bf9d72 -- permission denied for this window type
                                                                               at android.view.ViewRootImpl.setView(ViewRootImpl.java:609)
                                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:316)
                                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                               at com.xw.repo.BubbleSeekBar$2.onAnimationStart(BubbleSeekBar.java:484)
                                                                               at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1089)
                                                                               at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1048)
                                                                               at android.animation.ValueAnimator.start(ValueAnimator.java:1110)
                                                                               at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
                                                                               at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
                                                                               at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
                                                                               at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:486)
                                                                               at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:389)
                                                                               at android.view.View.dispatchTouchEvent(View.java:9306)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
                                                                               at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                               at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
                                                                               at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4278)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3830)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3887)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5970)
                                                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5944)
                                                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5905)
                                                                           	at android.view.ViewRootImpl$WindowInputE
12

**Comment by lwj1994** [comment]
Exception dispatching input event.
            12-07 09:39:11.891 6183-6183/com.xw.samlpe.bubbleseekbar E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
            12-07 09:39:11.892 6183-6183/com.xw.samlpe.bubbleseekbar E/MessageQueue-JNI: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7bf9d72 -- permission denied for this window type
                                                                                             at android.view.ViewRootImpl.setView(ViewRootImpl.java:609)
                                                                                             at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:316)
                                                                                             at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                                             at com.xw.repo.BubbleSeekBar$2.onAnimationStart(BubbleSeekBar.java:484)
                                                                                             at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1089)
                                                                                             at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1048)
                                                                                             at android.animation.ValueAnimator.start(ValueAnimator.java:1110)
                                                                                             at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
                                                                                             at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
                                                                                             at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
                                                                                             at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:486)
                                                                                             at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:389)
                                                                                             at android.view.View.dispatchTouchEvent(View.java:9306)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
                                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
                                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
                                                                                             at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4278)
                                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3830)
                                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3887)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5970)
                                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5944)
                                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5905)
                                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6073)
                                                                                         	at android.view.I
            12-07 09:39:11.893 6183-6183/com.xw.samlpe.bubbleseekbar D/AndroidRuntime: Shutting down VM
            12-07 09:39:11.893 6183-6183/com.xw.samlpe.bubbleseekbar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.xw.samlpe.bubbleseekbar, PID: 6183
                                                                                       android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7bf9d72 -- permission denied for this window type
                                                                                           at android.view.ViewRootImpl.setView(ViewRootImpl.java:609)
                                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:316)
                                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                                           at com.xw.repo.BubbleSeekBar$2.onAnimationStart(BubbleSeekBar.java:484)
                                                                                           at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1089)
                                                                                           at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1048)
                                                                                           at android.animation.ValueAnimator.start(ValueAnimator.java:1110)
                                                                                           at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
                                                                                           at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
                                                                                           at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
                                                                                           at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:486)
                                                                                           at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:389)
                                                                                           at android.view.View.dispatchTouchEvent(View.java:9306)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                           at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
                                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
                                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                           at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
                                                                                           at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4278)
                                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
                                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3830)
                                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3887)
                                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
                                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
                                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
                                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
                                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5970)
                                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5944)
                                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5905)
                                                                                       	at android.view.ViewRootImpl$WindowInputE
            12

**Comment by woxingxiao** [comment]
MIUI这个坑货造成的。v1.3已经做兼容了，请试试看
