### ISSUE TITLE
Unable to add window -- token null is not for an application

### ISSUE THREAD

**Issue by YouheiLee** [woxingxiao/BubbleSeekBar#104]
主要场景为开始拖动按钮直接crash，异常位置定位明确，但诱发的原因暂未查明。
手机型号： 小米 MIX，系统版本：MIUI 9.1.3.0  Android 7.0
<com.xw.repo.BubbleSeekBar
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="13dp"
            app:bsb_second_track_color="@color/order_finance_loan_seek_bar_enable_bg"
            app:bsb_second_track_size="5dp"
            app:bsb_section_text_color="@color/common_text_normal"
            app:bsb_thumb_color="@color/order_finance_loan_seek_bar_enable_btn_color"
            app:bsb_thumb_radius="5.5dp"
            app:bsb_thumb_radius_on_dragging="5.5dp"
            app:bsb_track_color="@color/order_finance_loan_seek_bar_enable_bg"
            app:bsb_track_size="5dp" />

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                         at android.view.ViewRootImpl.setView(ViewRootImpl.java:702)
                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                                                         at com.xw.repo.BubbleSeekBar$5.onAnimationStart(BubbleSeekBar.java:869)
                                                         at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1089)
                                                         at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:948)
                                                         at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1182)
                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:996)
                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
                                                         at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
                                                         at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
                                                         at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:871)
                                                         at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:683)
                                                         at android.view.View.dispatchTouchEvent(View.java:9955)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:3196)
                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                                                         at android.view.View.dispatchPointerEvent(View.java:10177)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4501)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4366)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4052)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4109)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
                                                     	at android.view.ViewRootImpl$InputStage.forward(Vi

**Comment by woxingxiao** [comment]
@YouheiLee 检查下你的Context是不是传成ApplicationContext了

**Comment by YouheiLee** [comment]
没有， 在华为P9上试过了 同样的xml写法 没有问题。另外只是在xml中写了，并没有写java代码

**Comment by woxingxiao** [comment]
@YouheiLee 我这里没有7.0的设备，我使用模拟器测试通过的。待我找个真机。。

**Comment by woxingxiao** [comment]
@YouheiLee 试了真机，7.0和8.0都没有问题。你下载sample.apk看看报没报错

**Comment by YouheiLee** [comment]
@woxingxiao 我仔细查了一下，由于我这边基础代码的封装有bug，导致这个地方最终context变成了AppllictionContext，修复之后没有这个问题了。

**Comment by YouheiLee** [comment]
谢谢您的耐心回复 @woxingxiao
