### ISSUE TITLE
IllegalStateException: BubbleView has already been added to the window manager

### ISSUE THREAD

**Issue by JohnSmithySmith** [woxingxiao/BubbleSeekBar#112]
**OS**
Appears only in API 14 and under every device. It works perfect in all versions above 19. I need to say that there's no code nor xml files that apply to seek bar and are dependent on API version.

**Description**
Seek bar displays fine but the app crashes right after touching it. If "touch to seek" is set then it makes to change progress. I mean the circle and the bar has the right position while "Unfortunately has stopped" box is showing if that'd be helpful.

**Crash log**
> E/AndroidRuntime(636): FATAL EXCEPTION: main
java.lang.IllegalStateException: View com.xw.repo.BubbleSeekBar$BubbleView@412ac108 has already been added to the window manager.
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:222)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:193)
at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:118)
at android.view.Window$LocalWindowManager.addView(Window.java:537)
at com.xw.repo.BubbleSeekBar$7.onAnimationStart(BubbleSeekBar.java:1007)
at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:804)
at android.animation.ValueAnimator.start(ValueAnimator.java:936)
at android.animation.ValueAnimator.start(ValueAnimator.java:950)
at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:644)
at android.view.ViewPropertyAnimator.access$100(ViewPropertyAnimator.java:48)
at android.view.ViewPropertyAnimator$1.run(ViewPropertyAnimator.java:147)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4340)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)

**XML**
```
<com.xw.repo.BubbleSeekBar
            app:bsb_max="100"
            app:bsb_min="0"
            app:bsb_section_count="10"
            app:bsb_section_text_interval="5"
            app:bsb_auto_adjust_section_mark="true"
            app:bsb_track_color="@color/actionBar"
            style="@style/SeekBar"/>
```
**styles.xml**
```
<style name="SeekBar">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="bsb_bubble_color">@color/bgContrast</item>
        <item name="bsb_bubble_text_color">@color/txtContrast</item>
        <item name="bsb_second_track_color">@color/txt</item>
        <item name="bsb_show_thumb_text">true</item>
        <item name="bsb_touch_to_seek">true</item>
        <item name="bsb_show_section_mark">true</item>
        <item name="bsb_section_text_position">below_section_mark</item>
        <item name="bsb_show_section_text">true</item>
</style>
```

**Comment by woxingxiao** [comment]
@JohnSmithySmith Thank you for your feedback. I didn't test it on api 14 until your issue arrived. It turns out running on under api 16 will occur the same problem, and I assume it is the system flaw. However, the market share under api 16 is nearing to 0, so it is unnecessary to consider them any longer. I will change the `minSdkVersion 14` to `minSdkVersion 16`.

**Comment by BrightVan** [comment]
在魅族的机器M3 note android 5.1也会报这个错误。
