### ISSUE TITLE
On Scroll

### ISSUE THREAD

**Issue by Dcodechef** [woxingxiao/BubbleSeekBar#12]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.xw.repo.BubbleSeekBar.correctOffsetWhenContainerOnScrolling()' on a null object reference
       at com.zinier.app.ui.fragments.questions.SlidingRatingFragment$2.onScrollChanged(SlidingRatingFragment.java:119)
       at android.view.ViewTreeObserver.dispatchOnScrollChanged(ViewTreeObserver.java:1016)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2514)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2446)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2079)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)

**Comment by woxingxiao** [comment]
I don't quite understand why your BubbleSeekBar's instance suddenly turns to null. Maybe you should do this:
```java  
if(mBubbleSeekBar != null) {
   mBubbleSeekBar.correctOffsetWhenContainerOnScrolling();
}
```
