### ISSUE TITLE
7.0魅族手机手机崩溃

### ISSUE THREAD

**Issue by zenfly** [woxingxiao/BubbleSeekBar#156]
java.lang.IllegalStateException: View com.xw.repo.BubbleSeekBar$BubbleView{c839d15 V.ED..... ......ID 0,0-0,0} has already been added to the window manager.
                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:330)
                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                          at com.xw.repo.BubbleSeekBar$7.onAnimationStart(BubbleSeekBar.java:1020)
                                                                          at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1110)
                                                                          at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:948)
                                                                          at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1182)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:996)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
                                                                          at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:924)
                                                                          at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:423)
                                                                          at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:1022)
                                                                          at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:695)
                                                                          at android.view.View.dispatchTouchEvent(View.java:10128)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
                                                                          at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:437)
                                                                          at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1841)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:3099)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                          at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
                                                                          at android.view.View.dispatchPointerEvent(View.java:10359)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5032)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4865)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4385)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4351)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4498)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4359)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4555)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4385)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4351)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4359)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6947)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6921)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6864)

**Comment by woxingxiao** [comment]
@zenfly 是最新3.19版吗？

**Comment by zenfly** [comment]
@woxingxiao 3.19-lite

**Comment by woxingxiao** [comment]
收到
