### ISSUE TITLE
Crash on fast scroll

### ISSUE THREAD

**Issue by coolmyll** [woxingxiao/BubbleSeekBar#16]
I have a material dialog in a fragment and the second time it is created if i try to scroll the seekbar immediately after its creation it crashes with this error:
`03-08 18:10:17.986 4027-4027/com.tea2code.e_gym E/InputEventReceiver: Exception dispatching input event.
03-08 18:10:17.986 4027-4027/com.tea2code.e_gym E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
03-08 18:10:17.990 4027-4027/com.tea2code.e_gym E/MessageQueue-JNI: android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@b8ed3ad has already been added
                                                                        at android.view.ViewRootImpl.setView(ViewRootImpl.java:691)
                                                                        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                                                                        at com.xw.repo.BubbleSeekBar$4.onAnimationStart(BubbleSeekBar.java:584)
                                                                        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1089)
                                                                        at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:951)
                                                                        at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1186)
                                                                        at android.animation.ValueAnimator.start(ValueAnimator.java:1000)
                                                                        at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
                                                                        at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
                                                                        at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
                                                                        at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:586)
                                                                        at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:430)
                                                                        at android.view.View.dispatchTouchEvent(View.java:10024)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
                                                                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                        at android.app.Dialog.dispatchTouchEvent(Dialog.java:799)
                                                                        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
                                                                        at android.view.View.dispatchPointerEvent(View.java:10244)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6252)
                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6226)
                                                                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6187)
                                                                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6355)
                                                                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                    	at android.os.MessageQueue.next(Me`

My code is like this:

`dialog = new MaterialDialog.Builder(getActivity())
                .title(getString(R.string.search_dialog_distance))
                .customView(R.layout.distance_dialog, true)
                .positiveText(getString(android.R.string.search_go))
                .negativeText(android.R.string.cancel)
                .cancelListener(new DialogInterface.OnCancelListener() {
                    @Override
                    public void onCancel(DialogInterface dialog) {

                        try {
                            progressBar.setVisibility(View.GONE);
                            location.setVisibility(View.VISIBLE);
                            location.setImageDrawable(ContextCompat.getDrawable(getContext(), R.drawable.places_ic_search));
                            location.setAlpha(0.5f);
                            Toast.makeText(getActivity(), getString(R.string.search_dialog_cancel), Toast.LENGTH_LONG).show();
                        } catch (Exception e) {
                            Log.e("Changed Tab", "KM List:" + e.getMessage());
                        }
                    }
                })
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        Toast.makeText(getActivity(), Integer.toString(distance), Toast.LENGTH_LONG).show();
                        task = new AsyncCaller();
                        task.execute();
                    }
                }).build();

                mBubbleSeekBar = (BubbleSeekBar) dialog.findViewById(R.id.bubble_seek_bar);
                distance = mBubbleSeekBar.getProgress();
                mBubbleSeekBar.setOnProgressChangedListener(new BubbleSeekBar.OnProgressChangedListenerAdapter() {
                @Override
                public void onProgressChanged(int progress) {
                    distance = progress;
                }
                });

                dialog.show();`

**Comment by woxingxiao** [comment]
It is strange. Have you tried to use `AlertDialog` instead of `MaterialDialog` ?

**Comment by coolmyll** [comment]
No i havent. I managed to use another simpler library to do it but your library seemed cooler.

It is strange cause it only happens if you click fast after the creation of the dialog. Maybe something about the animation causing it.

**Comment by woxingxiao** [comment]
What's api version of your phone ?

**Comment by coolmyll** [comment]
Latest. I have android 7.1.1

**Comment by woxingxiao** [comment]
Can you delete those `Toast` code? See what's going to happened.

**Comment by coolmyll** [comment]
I changed the code drastically so was probably an error on my end. Sorry about that.

**Comment by woxingxiao** [comment]
It turns out that Google has a more strict policy about toast type window using since Android 7.1.1, [detail here](https://android.googlesource.com/platform/frameworks/base/+/dc24f93). I've fixed it already in the latest version.
