### ISSUE TITLE
java.lang.NullPointerException: Attempt to write to field 'int android.view.WindowManager$LayoutParams.x' on a null object reference

### ISSUE THREAD

**Issue by muhammadzadeh** [woxingxiao/BubbleSeekBar#34]
@woxingxiao 
@VankaIn 

java.lang.NullPointerException: Attempt to write to field 'int android.view.WindowManager$LayoutParams.x' on a null object reference
	at .BubbleSeekBar.BubbleSeekBar$5.onAnimationUpdate(BubbleSeekBar.java:780)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
	at android.animation.AnimatorSet.start(AnimatorSet.java:586)
	at BubbleSeekBar.BubbleSeekBar.autoAdjustSection(BubbleSeekBar.java:833)
	at .BubbleSeekBar.BubbleSeekBar.access$100(BubbleSeekBar.java:48)
	at.BubbleSeekBar.BubbleSeekBar$2.run(BubbleSeekBar.java:624)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by woxingxiao** [comment]
Could you please tell me the specific scenario when this crash happened?

**Comment by muhammadzadeh** [comment]
I have a Listview that contain bubble seekbar,like attached photo.
Sometimes when i touch any bubble seekbar  #34 error occurred .

![photo_2017-07-22_15-34-48](https://user-images.githubusercontent.com/10474363/28490610-8cd6b0be-6ef3-11e7-94f4-c018d7b99e13.jpg)

**Comment by woxingxiao** [comment]
Is your language Arabic? The `BubbleSeekBar` haven't been adapted to right-to-left screen yet.

**Comment by muhammadzadeh** [comment]
Persian
