### ISSUE TITLE
The Sample.apk is can't open with HUAWEI 5A.

### ISSUE THREAD

**Issue by didikeeLunaon** [woxingxiao/BubbleSeekBar#37]
when i touch the launch icon,the crash.please fix it.thx

then,i try with my other phone.
```
HUAWEI C8817E 
SAMSUNG S7
```
is also crash.

**Comment by woxingxiao** [comment]
Can I have your crash log ?

**Comment by kylin17** [comment]
Me too.
Crash log:
```
com.xw.samlpe.bubbleseekbar E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.xw.samlpe.bubbleseekbar, PID: 26976
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.xw.samlpe.bubbleseekbar/com.xw.samlpe.bubbleseekbar.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.xw.samlpe.bubbleseekbar.MainActivity" on path: DexPathList[[zip file "/data/app/com.xw.samlpe.bubbleseekbar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xw.samlpe.bubbleseekbar-1/lib/arm64, /system/lib64, /vendor/lib64]]
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2590)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:160)
    at android.app.ActivityThread.main(ActivityThread.java:6200)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xw.samlpe.bubbleseekbar.MainActivity" on path: DexPathList[[zip file "/data/app/com.xw.samlpe.bubbleseekbar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xw.samlpe.bubbleseekbar-1/lib/arm64, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2580)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:160) 
    at android.app.ActivityThread.main(ActivityThread.java:6200) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
```

**Comment by woxingxiao** [comment]
@didikeeLunaon @kylin17 Hey guys, sorry for your trouble, the problem has been resolved. Please try the newest sample.
