### ISSUE TITLE
百分一百崩溃

### ISSUE THREAD

**Issue by catroom** [woxingxiao/BubbleSeekBar#4]
频繁的点击滑动点，立马崩溃。。

##   java.lang.IllegalStateException: View com.huarui.herolife.widget.BubbleSeekBar$BubbleView{b10e02 V.ED.... ......ID 0,0-126,126} has already been added to the window manager.
                                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:253)
                                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                         at com.huarui.herolife.widget.BubbleSeekBar$2.onAnimationStart(BubbleSeekBar.java:495)
                                                                         at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1111)
                                                                         at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:925)
                                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:962)
                                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:969)
                                                                         at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:925)
                                                                         at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:425)
                                                                         at com.huarui.herolife.widget.BubbleSeekBar.showBubble(BubbleSeekBar.java:497)
                                                                         at com.huarui.herolife.widget.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:396)

**Comment by catroom** [comment]
搞定了，在addview前面一定要remove view。即使频繁点击滑动点也不会崩溃了
 # if (mBubbleView.getParent() != null) {
                       #     mWindowManager.removeView(mBubbleView);
                       #     }
  mWindowManager.addView(mBubbleView, mLayoutParams);

**Comment by woxingxiao** [comment]
刚发布的`v1.4`已经完美解决了
