### ISSUE TITLE
NullPointterException    

### ISSUE THREAD

**Issue by xiaozhao0331** [woxingxiao/BubbleSeekBar#43]
java.lang.NullPointerException
	at com.xw.repo.BubbleSeekBar.onMeasure(BubbleSeekBar.java)
	at android.view.View.measure(View.java:16555)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
	at android.view.View.measure(View.java:16555)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
	at android.view.View.measure(View.java:16555)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
	at android.view.View.measure(View.java:16555)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1999)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1356)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1058)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5974)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
	at android.view.Choreographer.doCallbacks(Choreographer.java:593)
	at android.view.Choreographer.doFrame(Choreographer.java:562)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5315)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by woxingxiao** [comment]
以现在的信息无法定位异常。请问使用场景是什么？

**Comment by xiaozhao0331** [comment]
我暂时也没有办法定位  只是友盟统计上边显示有一个崩溃日志 我看错误是BubbleSeekBar的问题   
使用场景的话，我们是在一个答题页面  答题结束后我们会显示一个难度选择的弹框     大概就是这样

**Comment by woxingxiao** [comment]
从日志来看，父容器RelativeLayout调用measureChildHorizontal的时候，BubbleSeekBar的实例是null。你在手机上多次测试看能不能复现这个问题。

**Comment by xiaozhao0331** [comment]
好的   我试一下  然后再回复你

**Comment by eagle7758** [comment]
NullPointterException
