### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by samaryaumesh** [woxingxiao/BubbleSeekBar#49]
java.lang.NullPointerException: Attempt to write to field 'int android.view.WindowManager$LayoutParams.x' on a null object reference
                                             at com.xw.repo.BubbleSeekBar$6.onAnimationUpdate(BubbleSeekBar.java:826)
                                             at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1374)
                                             at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:602)
                                             at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:550)
                                             at android.animation.ValueAnimator.start(ValueAnimator.java:1039)
                                             at android.animation.ValueAnimator.start(ValueAnimator.java:1050)
                                             at android.animation.AnimatorSet.start(AnimatorSet.java:585)
                                             at com.xw.repo.BubbleSeekBar.autoAdjustSection(BubbleSeekBar.java:884)
                                             at com.xw.repo.BubbleSeekBar.access$100(BubbleSeekBar.java:49)
                                             at com.xw.repo.BubbleSeekBar$2.run(BubbleSeekBar.java:648)
                                             at android.os.Handler.handleCallback(Handler.java:815)
                                             at android.os.Handler.dispatchMessage(Handler.java:104)
                                             at android.os.Looper.loop(Looper.java:194)
                                             at android.app.ActivityThread.main(ActivityThread.java:5631)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by woxingxiao** [comment]
What's the specific scenario when this crash happened?

**Comment by samaryaumesh** [comment]
how to change selected point, some time provide NullPointerException

**Comment by woxingxiao** [comment]
Show me your xml or java code you used, please

**Comment by UltFlash** [comment]
我也遇到了同样的问题
Process: com.koalareading.koalareading, PID: 16467
                                                                               java.lang.NullPointerException: Attempt to write to field 'int android.view.WindowManager$LayoutParams.x' on a null object reference
                                                                                   at com.xw.repo.BubbleSeekBar$6.onAnimationUpdate(BubbleSeekBar.java:826)
                                                                                   at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
                                                                                   at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:612)
                                                                                   at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:578)
                                                                                   at android.animation.ValueAnimator.start(ValueAnimator.java:1001)
                                                                                   at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
                                                                                   at android.animation.AnimatorSet.start(AnimatorSet.java:678)
                                                                                   at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
                                                                                   at android.animation.AnimatorSet.start(AnimatorSet.java:640)
                                                                                   at com.xw.repo.BubbleSeekBar.autoAdjustSection(BubbleSeekBar.java:884)
                                                                                   at com.xw.repo.BubbleSeekBar.access$100(BubbleSeekBar.java:49)
                                                                                   at com.xw.repo.BubbleSeekBar$2.run(BubbleSeekBar.java:648)
                                                                                   at android.os.Handler.handleCallback(Handler.java:761)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:156)


我的xml文件是这样的
            <com.xw.repo.BubbleSeekBar
                android:id="@+id/bsb_feeling"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:bsb_auto_adjust_section_mark="true"
                app:bsb_is_float_type="true"
                app:bsb_second_track_color="#dcdcdc"
                app:bsb_second_track_size="3dp"
                app:bsb_section_count="2"
                app:bsb_section_text_position="below_section_mark"
                app:bsb_show_progress_in_float="true"
                app:bsb_show_section_mark="true"
                app:bsb_show_thumb_text="true"
                app:bsb_thumb_text_size="18sp"
                app:bsb_touch_to_seek="true"
                app:bsb_track_color="#dcdcdc"
                app:bsb_track_size="3dp"/>

跟seekbar相关的java代码如下：
bubbleSeekBar.setOnProgressChangedListener(new BubbleSeekBar.OnProgressChangedListener() {
            @Override
            public void onProgressChanged(int progress, float progressFloat) {

            }

            @Override
            public void getProgressOnActionUp(int progress, float progressFloat) {

            }

            @Override
            public void getProgressOnFinally(int progress, float progressFloat) {
                switch (progress) {
                    case 0:
                        tvFeeling.setText("感觉毫无压力");
                        feeling = "easy";
                        difficultyId = "1";
                        break;
                    case 50:
                        feeling = "normal";
                        difficultyId = "2";
                        tvFeeling.setText("感觉刚刚好");
                        break;

                    case 100:
                        tvFeeling.setText("感觉大脑被掏空");
                        feeling = "difficult";
                        difficultyId = "3";
                        break;
                }
            }
        });
麻烦帮忙看看是什么原因呢？谢谢！

**Comment by samaryaumesh** [comment]
my xml

<com.xw.repo.BubbleSeekBar
            android:id="@+id/my_seekbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            app:bsb_auto_adjust_section_mark="true"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            app:bsb_always_show_bubble="false"
            app:bsb_bubble_color="#00000000"
            app:bsb_bubble_text_color="#00000000"
            app:bsb_second_track_color="@color/colorPrimary"
            app:bsb_section_count="4"
            app:bsb_min="0"
            app:bsb_max="400"
            app:bsb_section_text_position="below_section_mark"
            app:bsb_show_section_mark="true"
            app:bsb_show_section_text="true"
            app:bsb_show_thumb_text="true"
            app:bsb_thumb_text_size="18sp"
            app:bsb_thumb_radius="10dp"
            app:bsb_touch_to_seek="true"/>

         mySeekBar.setProgress(mySeekBar.getMax());
        mySeekBar.setOnProgressChangedListener(new BubbleSeekBar.OnProgressChangedListener() {
            @Override
            public void onProgressChanged(int progress, float progressFloat) {

            }

            @Override
            public void getProgressOnActionUp(int progress, float progressFloat) {

            }

            @Override
            public void getProgressOnFinally(int progress, float progressFloat) {

                if(seekBarValue != progress){
                    seekBarValue = progress;
                   
            }
        });

**Comment by woxingxiao** [comment]
@UltFlash 你按下和滑动气泡显示是正常的吗？只有抬手才会报错吗？报错几率有多大？

**Comment by UltFlash** [comment]
是的，抬手的时候会报错，大概10次中就会有1，2次

**Comment by woxingxiao** [comment]
@VankaIn 
I guess you want to make the Bubble disappearing, try this:
```xml
    <com.xw.repo.BubbleSeekBar
        android:id="@+id/my_seekbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"
        android:layout_marginTop="8dp"
        app:bsb_auto_adjust_section_mark="true"
        app:bsb_hide_bubble="true"  <!-- use this attr -->
        app:bsb_max="400"
        app:bsb_min="0"
        app:bsb_section_count="4"
        app:bsb_section_text_position="below_section_mark"
        app:bsb_show_section_mark="true"
        app:bsb_show_section_text="true"
        app:bsb_show_thumb_text="true"
        app:bsb_thumb_radius="10dp"
        app:bsb_thumb_text_size="18sp"
        app:bsb_touch_to_seek="true"/>
```
It has no chance to throw that NullPointerException.

----

@UltFlash 
我试过你的布局和代码，不能复现这个异常。按道理讲，如果气泡出现过，WindowManager$LayoutParams就不为Null了。你用的版本是什么，加强版还是轻量版？是否还有一些使用细节没说？

**Comment by samaryaumesh** [comment]
I also used 'com.xw.repo:bubbleseekbar:3.6'.
