### ISSUE TITLE
空指针 - 

### ISSUE THREAD

**Issue by koliong** [woxingxiao/BubbleSeekBar#55]
09-23 11:34:15.928 28879-28879/com.xw.samlpe.bubbleseekbar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.NullPointerException
                                                                                 at com.xw.repo.BubbleSeekBar.locatePositionOnScreen(BubbleSeekBar.java:401)
                                                                                 at com.xw.repo.BubbleSeekBar.onLayout(BubbleSeekBar.java:379)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                 at android.view.View.layout(View.java:14011)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4373)
                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1711)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:779)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:592)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:562)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:765)
                                                                                 at android.os.Handler.handleCallback(Handler.java:725)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5046)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

xml部分:
    <com.xw.repo.BubbleSeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        app:bsb_hide_bubble="true"
        app:bsb_auto_adjust_section_mark="true"
        app:bsb_second_track_color="@color/color_blue"
        app:bsb_section_count="3"
        app:bsb_show_section_mark="true"
        app:bsb_thumb_text_size="18sp"
        app:bsb_touch_to_seek="true"
        app:bsb_track_color="@color/color_gray"/>

app:bsb_hide_bubble="true"不设置时不出异常。

**Comment by koliong** [comment]
经过调试，在Line:378增加判断

        if (isHideBubble)
            return;

即可解决。
