### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by zhaoyouzhi** [woxingxiao/BubbleSeekBar#65]
FATAL EXCEPTION: main
                                                                           Process: com.gxsn.mdc.professional, PID: 14042
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'int com.xw.repo.BubbleSeekBar$BubbleView.getMeasuredWidth()' on a null object reference
                                                                               at com.xw.repo.BubbleSeekBar.locatePositionOnScreen(BubbleSeekBar.java:400)
                                                                               at com.xw.repo.BubbleSeekBar.onLayout(BubbleSeekBar.java:378)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.widget.ScrollView.onLayout(ScrollView.java:1505)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.view.View.layout(View.java:15689)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2116)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                           	at android.view.Chor

**Comment by zhaoyouzhi** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.xw.repo.BubbleSeekBar
        android:id="@+id/item_assessment_seek_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        app:bsb_auto_adjust_section_mark="true"
        app:bsb_hide_bubble="true"
        app:bsb_max="5"
        app:bsb_min="0"
        app:bsb_second_track_color="@color/colorPrimary"
        app:bsb_section_count="5"
        app:bsb_show_section_mark="true"
        app:bsb_touch_to_seek="true" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:text="@string/assessment_abnormal"
            android:textSize="@dimen/text" />

        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1" />

        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1" />

        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1" />

        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="end"
            android:text="@string/assessment_normal"
            android:textSize="@dimen/text" />

        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="end"
            android:text="@string/assessment_improve"
            android:textSize="@dimen/text" />


    </LinearLayout>
</LinearLayout>

**Comment by zhaoyouzhi** [comment]
初始化的时候就崩溃了

**Comment by woxingxiao** [comment]
用最新版3.7

**Comment by zhaoyouzhi** [comment]
'com.xw.repo:bubbleseekbar:3.7-lite'

**Comment by zhaoyouzhi** [comment]
private void locatePositionOnScreen() {
        this.getLocationOnScreen(this.mPoint);
        this.mBubbleCenterRawSolidX = (float)this.mPoint[0] + this.mLeft - (float)**this.mBubbleView**.getMeasuredWidth() / 2.0F; （为空）
        this.mBubbleCenterRawX = this.mBubbleCenterRawSolidX + this.mTrackLength * (this.mProgress - this.mMin) / this.mDelta;
        this.mBubbleCenterRawSolidY = (float)(this.mPoint[1] - this.mBubbleView.getMeasuredHeight());
        this.mBubbleCenterRawSolidY -= (float)BubbleUtils.dp2px(24);
        if(BubbleUtils.isMIUI()) {
            this.mBubbleCenterRawSolidY += (float)BubbleUtils.dp2px(4);
        }
    }

**Comment by woxingxiao** [comment]
`locatePositionOnScreen()`方法之前都有个判断：
```java
if (isHideBubble)
    return;
```
你debug看下`isHideBubble` 是true还是false

**Comment by zhaoyouzhi** [comment]
protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        super.onLayout(changed, left, top, right, bottom);
        this.locatePositionOnScreen();
    }
这个并没有判断。是因为 app:bsb_hide_bubble="true"引起的崩溃

**Comment by woxingxiao** [comment]
噢对，我改一下，晚上更新。多谢反馈。

**Comment by zhaoyouzhi** [comment]
我clone下来的demo有
if (isHideBubble)
    return;
是不是版本库还没有更新。
