### ISSUE TITLE
Crash in recyclerview.

### ISSUE THREAD

**Issue by hk4774** [woxingxiao/BubbleSeekBar#66]
Got a crash while using in recyclerview as below: 

` java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.measure(int, int)' on a null object reference
                                                                                        at com.xw.repo.BubbleSeekBar.onMeasure(BubbleSeekBar.java:387)
                                                                                        at android.view.View.measure(View.java:19756)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
                                                                                        at android.view.View.measure(View.java:19756)`

**Comment by woxingxiao** [comment]
RecyclerView or ListView is not supported.
