### ISSUE TITLE
Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by jiajieshen** [woxingxiao/BubbleSeekBar#67]
```
 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                        java.lang.Throwable: Explicit termination method 'close' not called
                                                                            at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                            at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                            at com.xw.repo.BubbleUtils.getBuildProperties(BubbleUtils.java:23)
                                                                            at com.xw.repo.BubbleUtils.isMIUI(BubbleUtils.java:33)
                                                                            at com.xw.repo.BubbleSeekBar.<init>(BubbleSeekBar.java:214)
                                                                            at com.xw.repo.BubbleSeekBar.<init>(BubbleSeekBar.java:127)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
```

**Comment by jiajieshen** [comment]
可以将 BubbleUtils.java 的输入流关闭一下
```java
    private static Properties getBuildProperties() {
        synchronized (sBuildPropertiesLock) {
            if (sBuildProperties == null) {
                sBuildProperties = new Properties();
                try {
                    sBuildProperties.load(new FileInputStream(BUILD_PROP_FILE));
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return sBuildProperties;
    }
```

**Comment by woxingxiao** [comment]
嗯，我也发现了，下个版本解决。感谢反馈。
