### ISSUE TITLE
Crash in ViewPager.

### ISSUE THREAD

**Issue by 823546371** [woxingxiao/BubbleSeekBar#68]
java.lang.IllegalArgumentException: view must not be null
                                                                            at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:304)
                                                                            at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:91)
                                                                            at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:675)
                                                                            at android.view.View.dispatchTouchEvent(View.java:8668)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                            at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1833)
                                                                            at android.view.View.dispatchPointerEvent(View.java:8874)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4729)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4587)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4139)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4105)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4242)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4113)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4299)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4139)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4105)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4113)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6543)
                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6517)
                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6470)
                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6723)
                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6661)
                                                                            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6749)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:570)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                        	at com.android.internal.os.ZygoteInit.main(Zygot

viewpager 再次回到这个页面的时候操作的时候挂了

**Comment by woxingxiao** [comment]
“viewpager 再次回到这个页面的时候” 这句话不太明白

**Comment by 823546371** [comment]
第一个页面滑动到第三个在滑动到第一个操作seekBar的时候就报上面的错误

**Comment by 759325100** [comment]
我也发现了这个问题，我的使用场景如下：
我将空间放在Dialog中（通过View.inflate载入到Dialog），第一次弹出可以正常使用控件第二次在弹出，拖动Seekbar就会出现这个异常，异常信息如下：
 FATAL EXCEPTION: main
                                                                                Process: com.umarbhutta.xlightcompanion, PID: 29930
                                                                                java.lang.IllegalArgumentException: view must not be null
                                                                                    at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:357)
                                                                                    at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
                                                                                    at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:675)
                                                                                    at android.view.View.dispatchTouchEvent(View.java:10731)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                                    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:509)
                                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:3226)
                                                                                    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:471)
                                                                                    at android.view.View.dispatchPointerEvent(View.java:10960)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5068)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4920)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4504)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4470)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4603)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4478)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4660)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4504)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4470)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4478)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
                                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6953)
                                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6892)
                                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6853)
                                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7063)
                                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7027)
                                                                                    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7090)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
11-20 11:03:50.762 29930-29930/com.umarbhutta.xlightcompanion E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:632)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by woxingxiao** [comment]
@759325100 库版本？

**Comment by 759325100** [comment]
@woxingxiao 
3.10-lite

**Comment by woxingxiao** [comment]
@759325100 ok，待我有空看看。

**Comment by 759325100** [comment]
如果需要我提供任何信息，我将全力配合。再次感谢 ~

**Comment by 759325100** [comment]
@woxingxiao 我尝试将lite版本切换成enhanced版本，问题消失，不知道这是否因为两个版本的不同导致的。我先这样处理该问题。

**Comment by woxingxiao** [comment]
@759325100 我看你出错的行数更我现在的行数未对应，这样处理下：注释build.gradle里依赖本库这一行->build->取消注释->build，再试试lite版，我怀疑是本地文件未刷新。

**Comment by 759325100** [comment]
确实，我clean项目之后，在重新rebuild一次，lite版本也是ok的。看来这个问题在最新版本的lite中也并不存在，感谢您的帮助，不尽感激 ~
