### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by 823546371** [woxingxiao/BubbleSeekBar#73]
java.lang.IllegalStateException: View com.xw.repo.BubbleSeekBar$BubbleView{514d8e7 V.ED.... ......ID 0,0-0,0} has already been added to the window manager.
                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:260)
                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                          at com.xw.repo.BubbleSeekBar$5.onAnimationStart(BubbleSeekBar.java:815)
                                                                          at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1111)
                                                                          at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:981)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:1043)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:1050)
                                                                          at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:925)
                                                                          at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:425)
                                                                          at com.xw.repo.BubbleSeekBar.showBubble(BubbleSeekBar.java:817)
                                                                          at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:629)
                                                                          at android.view.View.dispatchTouchEvent(View.java:8668)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                          at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1833)
                                                                          at android.view.View.dispatchPointerEvent(View.java:8874)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4729)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4587)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4139)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4105)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4242)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4113)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4299)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4139)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4105)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4113)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6543)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6517)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6470)
                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6723)
                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                          at android.os.MessageQueue.next(MessageQueue.java:148)
                                                                          at android.os.Looper.loop(Looper.java:151)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by woxingxiao** [comment]
请参照README.md中“怎样提出有效的issue”，如仍有问题再重新打开。
