### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by Hhh3S** [woxingxiao/BubbleSeekBar#79]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent com.gome.keychain.ui.widget.BubbleSeekBar$a.getParent()' on a null object reference
                                                                     at com.gome.keychain.ui.widget.BubbleSeekBar$5.onAnimationUpdate(BubbleSeekBar.java:801)
                                                                     at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
                                                                     at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1258)
                                                                     at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1306)
                                                                     at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
                                                                     at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
                                                                     at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:709)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:641)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
                                                                     at android.os.Handler.handleCallback(Handler.java:836)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                     at android.os.Looper.loop(Looper.java:203)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6362)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

![nullpointexception](https://user-images.githubusercontent.com/17513523/32685873-2cea4a28-c6d5-11e7-8f78-2ad9fd270b2a.png)

**Comment by woxingxiao** [comment]
使用的哪个版本

**Comment by Hhh3S** [comment]
忘记哪个版本了,我是拷贝源码使用的

**Comment by Hhh3S** [comment]
我是跑monkey跑出来了,正常人类使用没出现过这个问题

**Comment by woxingxiao** [comment]
什么时候拷贝的代码

**Comment by Hhh3S** [comment]
六七月份吧,我又拷贝了最新的源码还有问题再跟你说吧,Thankyou
