### ISSUE TITLE
您好,我在Dialog里使用BubbleSeekBar 时 出现如下异常

### ISSUE THREAD

**Issue by ZHDelete** [woxingxiao/BubbleSeekBar#83]
E/CrashReport: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.xw.repo.BubbleSeekBar$BubbleView.measure(int, int)' on a null object reference
                 at com.xw.repo.BubbleSeekBar.onMeasure(BubbleSeekBar.java:372)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                 at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1112)
                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                 at android.view.View.measure(View.java:18811)
                 at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                 at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                 at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                 at android.view.View.measure(View.java:18811)
                 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                 at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                 at android.view.Choreographer.doFrame(Choreographer.java:608)
                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                 at android.os.Handler.handleCallback(Handler.java:742)
                 at android.os.Handler.dispatchMessage(Handler.java:95)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.app.ActivityThread.main(ActivityThread.java:5527)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by woxingxiao** [comment]
不够具体，我无法定位问题。请参照README.md中“怎样提出有效的issue”，并告知使用的库版本。
