### ISSUE TITLE
运行Demo发现错误

### ISSUE THREAD

**Issue by gloryzgh** [woxingxiao/BubbleSeekBar#86]
在DemoFragment4 中的bubbleSeekBar4的使用中发现反复拉动会造成Demo程序崩溃,   机型:SM-G9350  android 7.0   崩溃日志如下:   `  Process: com.xw.samlpe.bubbleseekbar, PID: 7324
                                                                           java.lang.IllegalArgumentException: View=com.xw.repo.BubbleSeekBar$BubbleView{c821cea V.ED..... ......ID 0,0-144,144} not attached to window manager
                                                                               at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
                                                                               at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:368)
                                                                               at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
                                                                               at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:728)
                                                                               at android.view.View.dispatchTouchEvent(View.java:10731)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                                               at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:509)
                                                                               at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                                               at android.app.Activity.dispatchTouchEvent(Activity.java:3226)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                               at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:471)
                                                                               at android.view.View.dispatchPointerEvent(View.java:10960)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5068)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4920)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4504)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4470)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4603)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4478)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4660)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4504)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4470)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4478)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
                                                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6953)
                                                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6892)
                                                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6853)
                                                                               at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7063)
                                                                               at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                               at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                               at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                               at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7027)
11-24 10:41:43.956 7324-7324/com.xw.samlpe.bubbleseekbar E/AndroidRuntime:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7090)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:632)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
`

**Comment by woxingxiao** [comment]
已解决，感谢反馈。
